name: Run Python Script

on:
  schedule:
    - cron: '57 6 * * *'  # 每天 06:40 UTC 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 使用您需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests schedule  # 直接安装所需的库

      - name: Run script
        run: python policies_scraper.py  # 替换为您的脚本名称